# Generated by Django 3.2.9 on 2021-11-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0002_cards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='image',
            new_name='photo',
        ),
    ]
