# Generated by Django 3.2.9 on 2021-11-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0003_rename_image_cards_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutpic', models.ImageField(upload_to='about')),
                ('aboutdesc', models.TextField()),
            ],
        ),
    ]
